# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Measurement_Setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import UIpy.Measurement_Setup_rc


class Ui_Dialog_Measurement_Setup(object):
    def setupUi(self, Dialog_Measurement_Setup):
        Dialog_Measurement_Setup.setObjectName("Dialog_Measurement_Setup")
        Dialog_Measurement_Setup.resize(1250, 807)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Measurement_Setup.sizePolicy().hasHeightForWidth())
        Dialog_Measurement_Setup.setSizePolicy(sizePolicy)
        Dialog_Measurement_Setup.setMinimumSize(QtCore.QSize(1250, 354))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Measurement_Setup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog_Measurement_Setup)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_picture = QtWidgets.QLabel(self.frame)
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout_2.addWidget(self.label_picture)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Measurement_Setup)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_Measurement_Setup)
        self.buttonBox.accepted.connect(Dialog_Measurement_Setup.accept)
        self.buttonBox.rejected.connect(Dialog_Measurement_Setup.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Measurement_Setup)

    def retranslateUi(self, Dialog_Measurement_Setup):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Measurement_Setup.setWindowTitle(_translate("Dialog_Measurement_Setup", "Measurement Setup"))
        self.label_2.setText(_translate("Dialog_Measurement_Setup", "Measurement Setup Guide"))
        self.label_3.setText(_translate("Dialog_Measurement_Setup", "Diagram below shows the connection of the measurement.\n"
"Digital Multimeter (DMM) is optional if reading is directly taken from Power Supply and ELOAD.\n"
""))
        self.label_picture.setText(_translate("Dialog_Measurement_Setup", "<html><head/><body><p><img src=\":/Setup_pic/drawing.JPG\"/></p></body></html>"))
        self.label.setText(_translate("Dialog_Measurement_Setup", "Created @2021/5 version 1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Measurement_Setup = QtWidgets.QDialog()
    ui = Ui_Dialog_Measurement_Setup()
    ui.setupUi(Dialog_Measurement_Setup)
    Dialog_Measurement_Setup.show()
    sys.exit(app.exec_())
